name: GitHub → Discord

# Event ที่ trigger workflow
on:
  push:
    branches:
      - main           # เปลี่ยนตาม branch ของ repo
  pull_request:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send notification to Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          args: |
            {
              "username": "GitHub Bot",
              "embeds": [
                {
                  "title": "📢 GitHub Update",
                  "description": "Repository: **${{ github.repository }}**\nAction: **${{ github.event_name }}**\nUser: **${{ github.actor }}**\nCommit/PR/Release: `${{ github.sha }}`",
                  "color": 7506394
                }
              ]
            }
